# render.yaml

# Render tarafından desteklenen üst düzey anahtarlar: 'services', 'databases', 'redis'
# Tüm Web, Worker, Cron hizmetleri 'services' altına gider.

services:
  # 1. Web Servisi (Flask Uygulaması)
  - type: web
    name: task-manager-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      # DÜZELTME: type: psql yerine type: database kullanıldı.
      - key: DATABASE_URL
        fromService:
          type: database 
          name: task-manager-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString
      # ... diğer envVars

  # 2. Arka Plan Çalışanı (Celery Worker)
  - type: worker
    name: task-manager-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A app.celery worker --loglevel=info"
    envVars:
      # ... diğer envVars
      # DÜZELTME: type: psql yerine type: database kullanıldı.
      - key: DATABASE_URL
        fromService:
          type: database  
          name: task-manager-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString
      # ... diğer envVars

  # 3. Redis (Celery için)
  - type: redis
    name: task-manager-redis
    plan: free
    # NOT: services bloğundan "type: psql" tanımı tamamen kaldırıldı.

# PostgreSQL veritabanını tanımlamak için kullanılan doğru üst düzey blok budur.
databases:
  - name: task-manager-db
    plan: free
ipAllowList:
      - source: 0.0.0.0/0 # Tüm IP'lerden erişime izin verir (Dikkatli kullanın!)
        description: Dahili Render hizmetleri
    # Bu tanım, task-manager-db adlı bir PostgreSQL veritabanı oluşturacaktır.