# render.yaml

services:
  # 1. Web Servisi (Flask Uygulaması)
  - type: web
    name: task-manager-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    releaseCommand: "flask db upgrade"
    initialDeployHook: "flask db upgrade" # Sadece ilk kurulumda veritabanını oluşturmayı garanti eder
    startCommand: "gunicorn app:app" # Uygulamayı başlat
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString

  # 2. Zamanlanmış Görev (E-posta Hatırlatıcıları için)
  - type: cron
    name: email-reminders
    env: python
    buildCommand: "pip install -r requirements.txt" # Sadece kütüphaneleri kur
    schedule: "0 * * * *" # Her saatin başında çalışır (örneğin her saatin 0. dakikasında)
    startCommand: "python run_hourly_reminders.py" # Yeni Python scriptini çalıştır
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        fromService:
          type: web
          name: task-manager-web
          envVarKey: SECRET_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: task-manager-redis
          property: connectionString

  # 3. Redis Servisi (Celery için)
  - type: redis
    name: task-manager-redis
    plan: free
    ipAllowList: [] # Sadece Render içinden erişime izin verir.
    maxmemoryPolicy: allkeys-lru # Ücretsiz Redis planları için önerilir.

# PostgreSQL veritabanını tanımlamak için doğru üst düzey blok
databases:
  - name: task-manager-db
    plan: free