"""Add notes_deleted_count to User model

Revision ID: 15613a348ab4
Revises: f1cd17d30437
Create Date: 2025-10-21 10:20:30.676285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15613a348ab4'
down_revision = 'f1cd17d30437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes_deleted_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notes_deleted_count')

    # ### end Alembic commands ###
